export default {
  login: "ioannis-sporidis",
  id: 60279226,
  node_id: "MDQ6VXNlcjYwMjc5MjI2",
  avatar_url: "https://avatars.githubusercontent.com/u/60279226?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ioannis-sporidis",
  html_url: "https://github.com/ioannis-sporidis",
  followers_url: "https://api.github.com/users/ioannis-sporidis/followers",
  following_url:
    "https://api.github.com/users/ioannis-sporidis/following{/other_user}",
  gists_url: "https://api.github.com/users/ioannis-sporidis/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/ioannis-sporidis/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/ioannis-sporidis/subscriptions",
  organizations_url: "https://api.github.com/users/ioannis-sporidis/orgs",
  repos_url: "https://api.github.com/users/ioannis-sporidis/repos",
  events_url: "https://api.github.com/users/ioannis-sporidis/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/ioannis-sporidis/received_events",
  type: "User",
  site_admin: false,
  name: "Ioannis Sporidis",
  company: null,
  blog: "http://www.ioannis-sporidis.com/",
  location: "Pittsburgh, PA",
  email: null,
  hireable: true,
  bio: "Full-stack web developer with a background in education and passionate about creating user-friendly web experiences. ",
  twitter_username: "the_fetaverse",
  public_repos: 44,
  public_gists: 0,
  followers: 18,
  following: 27,
  created_at: "2020-01-25T01:27:49Z",
  updated_at: "2021-12-14T14:54:56Z",
};
