export default [
  {
    login: "elefthei",
    id: 766892,
    node_id: "MDQ6VXNlcjc2Njg5Mg==",
    avatar_url: "https://avatars.githubusercontent.com/u/766892?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/elefthei",
    html_url: "https://github.com/elefthei",
    followers_url: "https://api.github.com/users/elefthei/followers",
    following_url:
      "https://api.github.com/users/elefthei/following{/other_user}",
    gists_url: "https://api.github.com/users/elefthei/gists{/gist_id}",
    starred_url: "https://api.github.com/users/elefthei/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/elefthei/subscriptions",
    organizations_url: "https://api.github.com/users/elefthei/orgs",
    repos_url: "https://api.github.com/users/elefthei/repos",
    events_url: "https://api.github.com/users/elefthei/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/elefthei/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Jefftopia",
    id: 5161547,
    node_id: "MDQ6VXNlcjUxNjE1NDc=",
    avatar_url: "https://avatars.githubusercontent.com/u/5161547?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Jefftopia",
    html_url: "https://github.com/Jefftopia",
    followers_url: "https://api.github.com/users/Jefftopia/followers",
    following_url:
      "https://api.github.com/users/Jefftopia/following{/other_user}",
    gists_url: "https://api.github.com/users/Jefftopia/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Jefftopia/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Jefftopia/subscriptions",
    organizations_url: "https://api.github.com/users/Jefftopia/orgs",
    repos_url: "https://api.github.com/users/Jefftopia/repos",
    events_url: "https://api.github.com/users/Jefftopia/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Jefftopia/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "muzhaqi16",
    id: 7892020,
    node_id: "MDQ6VXNlcjc4OTIwMjA=",
    avatar_url: "https://avatars.githubusercontent.com/u/7892020?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/muzhaqi16",
    html_url: "https://github.com/muzhaqi16",
    followers_url: "https://api.github.com/users/muzhaqi16/followers",
    following_url:
      "https://api.github.com/users/muzhaqi16/following{/other_user}",
    gists_url: "https://api.github.com/users/muzhaqi16/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/muzhaqi16/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/muzhaqi16/subscriptions",
    organizations_url: "https://api.github.com/users/muzhaqi16/orgs",
    repos_url: "https://api.github.com/users/muzhaqi16/repos",
    events_url: "https://api.github.com/users/muzhaqi16/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/muzhaqi16/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "BrianLevin",
    id: 40183054,
    node_id: "MDQ6VXNlcjQwMTgzMDU0",
    avatar_url: "https://avatars.githubusercontent.com/u/40183054?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/BrianLevin",
    html_url: "https://github.com/BrianLevin",
    followers_url: "https://api.github.com/users/BrianLevin/followers",
    following_url:
      "https://api.github.com/users/BrianLevin/following{/other_user}",
    gists_url: "https://api.github.com/users/BrianLevin/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/BrianLevin/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/BrianLevin/subscriptions",
    organizations_url: "https://api.github.com/users/BrianLevin/orgs",
    repos_url: "https://api.github.com/users/BrianLevin/repos",
    events_url: "https://api.github.com/users/BrianLevin/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/BrianLevin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dolinay1",
    id: 43730139,
    node_id: "MDQ6VXNlcjQzNzMwMTM5",
    avatar_url: "https://avatars.githubusercontent.com/u/43730139?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dolinay1",
    html_url: "https://github.com/dolinay1",
    followers_url: "https://api.github.com/users/dolinay1/followers",
    following_url:
      "https://api.github.com/users/dolinay1/following{/other_user}",
    gists_url: "https://api.github.com/users/dolinay1/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dolinay1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dolinay1/subscriptions",
    organizations_url: "https://api.github.com/users/dolinay1/orgs",
    repos_url: "https://api.github.com/users/dolinay1/repos",
    events_url: "https://api.github.com/users/dolinay1/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/dolinay1/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "K3vinDi3s3l",
    id: 58582807,
    node_id: "MDQ6VXNlcjU4NTgyODA3",
    avatar_url: "https://avatars.githubusercontent.com/u/58582807?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/K3vinDi3s3l",
    html_url: "https://github.com/K3vinDi3s3l",
    followers_url: "https://api.github.com/users/K3vinDi3s3l/followers",
    following_url:
      "https://api.github.com/users/K3vinDi3s3l/following{/other_user}",
    gists_url: "https://api.github.com/users/K3vinDi3s3l/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/K3vinDi3s3l/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/K3vinDi3s3l/subscriptions",
    organizations_url: "https://api.github.com/users/K3vinDi3s3l/orgs",
    repos_url: "https://api.github.com/users/K3vinDi3s3l/repos",
    events_url: "https://api.github.com/users/K3vinDi3s3l/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/K3vinDi3s3l/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ksmera01",
    id: 58998325,
    node_id: "MDQ6VXNlcjU4OTk4MzI1",
    avatar_url: "https://avatars.githubusercontent.com/u/58998325?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ksmera01",
    html_url: "https://github.com/ksmera01",
    followers_url: "https://api.github.com/users/ksmera01/followers",
    following_url:
      "https://api.github.com/users/ksmera01/following{/other_user}",
    gists_url: "https://api.github.com/users/ksmera01/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ksmera01/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ksmera01/subscriptions",
    organizations_url: "https://api.github.com/users/ksmera01/orgs",
    repos_url: "https://api.github.com/users/ksmera01/repos",
    events_url: "https://api.github.com/users/ksmera01/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ksmera01/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jasonstevens13",
    id: 59122680,
    node_id: "MDQ6VXNlcjU5MTIyNjgw",
    avatar_url: "https://avatars.githubusercontent.com/u/59122680?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jasonstevens13",
    html_url: "https://github.com/jasonstevens13",
    followers_url: "https://api.github.com/users/jasonstevens13/followers",
    following_url:
      "https://api.github.com/users/jasonstevens13/following{/other_user}",
    gists_url: "https://api.github.com/users/jasonstevens13/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jasonstevens13/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/jasonstevens13/subscriptions",
    organizations_url: "https://api.github.com/users/jasonstevens13/orgs",
    repos_url: "https://api.github.com/users/jasonstevens13/repos",
    events_url: "https://api.github.com/users/jasonstevens13/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jasonstevens13/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "wayele",
    id: 59747345,
    node_id: "MDQ6VXNlcjU5NzQ3MzQ1",
    avatar_url: "https://avatars.githubusercontent.com/u/59747345?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/wayele",
    html_url: "https://github.com/wayele",
    followers_url: "https://api.github.com/users/wayele/followers",
    following_url: "https://api.github.com/users/wayele/following{/other_user}",
    gists_url: "https://api.github.com/users/wayele/gists{/gist_id}",
    starred_url: "https://api.github.com/users/wayele/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/wayele/subscriptions",
    organizations_url: "https://api.github.com/users/wayele/orgs",
    repos_url: "https://api.github.com/users/wayele/repos",
    events_url: "https://api.github.com/users/wayele/events{/privacy}",
    received_events_url: "https://api.github.com/users/wayele/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jbenj-upenn",
    id: 59940368,
    node_id: "MDQ6VXNlcjU5OTQwMzY4",
    avatar_url: "https://avatars.githubusercontent.com/u/59940368?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jbenj-upenn",
    html_url: "https://github.com/jbenj-upenn",
    followers_url: "https://api.github.com/users/jbenj-upenn/followers",
    following_url:
      "https://api.github.com/users/jbenj-upenn/following{/other_user}",
    gists_url: "https://api.github.com/users/jbenj-upenn/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jbenj-upenn/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jbenj-upenn/subscriptions",
    organizations_url: "https://api.github.com/users/jbenj-upenn/orgs",
    repos_url: "https://api.github.com/users/jbenj-upenn/repos",
    events_url: "https://api.github.com/users/jbenj-upenn/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jbenj-upenn/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "stmiller57",
    id: 60395221,
    node_id: "MDQ6VXNlcjYwMzk1MjIx",
    avatar_url: "https://avatars.githubusercontent.com/u/60395221?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/stmiller57",
    html_url: "https://github.com/stmiller57",
    followers_url: "https://api.github.com/users/stmiller57/followers",
    following_url:
      "https://api.github.com/users/stmiller57/following{/other_user}",
    gists_url: "https://api.github.com/users/stmiller57/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/stmiller57/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/stmiller57/subscriptions",
    organizations_url: "https://api.github.com/users/stmiller57/orgs",
    repos_url: "https://api.github.com/users/stmiller57/repos",
    events_url: "https://api.github.com/users/stmiller57/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/stmiller57/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dooski",
    id: 60619919,
    node_id: "MDQ6VXNlcjYwNjE5OTE5",
    avatar_url: "https://avatars.githubusercontent.com/u/60619919?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dooski",
    html_url: "https://github.com/dooski",
    followers_url: "https://api.github.com/users/dooski/followers",
    following_url: "https://api.github.com/users/dooski/following{/other_user}",
    gists_url: "https://api.github.com/users/dooski/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dooski/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dooski/subscriptions",
    organizations_url: "https://api.github.com/users/dooski/orgs",
    repos_url: "https://api.github.com/users/dooski/repos",
    events_url: "https://api.github.com/users/dooski/events{/privacy}",
    received_events_url: "https://api.github.com/users/dooski/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "kaito47",
    id: 60710299,
    node_id: "MDQ6VXNlcjYwNzEwMjk5",
    avatar_url: "https://avatars.githubusercontent.com/u/60710299?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kaito47",
    html_url: "https://github.com/kaito47",
    followers_url: "https://api.github.com/users/kaito47/followers",
    following_url:
      "https://api.github.com/users/kaito47/following{/other_user}",
    gists_url: "https://api.github.com/users/kaito47/gists{/gist_id}",
    starred_url: "https://api.github.com/users/kaito47/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kaito47/subscriptions",
    organizations_url: "https://api.github.com/users/kaito47/orgs",
    repos_url: "https://api.github.com/users/kaito47/repos",
    events_url: "https://api.github.com/users/kaito47/events{/privacy}",
    received_events_url: "https://api.github.com/users/kaito47/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "TLGeorge",
    id: 60828138,
    node_id: "MDQ6VXNlcjYwODI4MTM4",
    avatar_url: "https://avatars.githubusercontent.com/u/60828138?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/TLGeorge",
    html_url: "https://github.com/TLGeorge",
    followers_url: "https://api.github.com/users/TLGeorge/followers",
    following_url:
      "https://api.github.com/users/TLGeorge/following{/other_user}",
    gists_url: "https://api.github.com/users/TLGeorge/gists{/gist_id}",
    starred_url: "https://api.github.com/users/TLGeorge/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/TLGeorge/subscriptions",
    organizations_url: "https://api.github.com/users/TLGeorge/orgs",
    repos_url: "https://api.github.com/users/TLGeorge/repos",
    events_url: "https://api.github.com/users/TLGeorge/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/TLGeorge/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ravalash",
    id: 60895755,
    node_id: "MDQ6VXNlcjYwODk1NzU1",
    avatar_url: "https://avatars.githubusercontent.com/u/60895755?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ravalash",
    html_url: "https://github.com/ravalash",
    followers_url: "https://api.github.com/users/ravalash/followers",
    following_url:
      "https://api.github.com/users/ravalash/following{/other_user}",
    gists_url: "https://api.github.com/users/ravalash/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ravalash/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ravalash/subscriptions",
    organizations_url: "https://api.github.com/users/ravalash/orgs",
    repos_url: "https://api.github.com/users/ravalash/repos",
    events_url: "https://api.github.com/users/ravalash/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ravalash/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ecn2318",
    id: 60996793,
    node_id: "MDQ6VXNlcjYwOTk2Nzkz",
    avatar_url: "https://avatars.githubusercontent.com/u/60996793?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ecn2318",
    html_url: "https://github.com/ecn2318",
    followers_url: "https://api.github.com/users/ecn2318/followers",
    following_url:
      "https://api.github.com/users/ecn2318/following{/other_user}",
    gists_url: "https://api.github.com/users/ecn2318/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ecn2318/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ecn2318/subscriptions",
    organizations_url: "https://api.github.com/users/ecn2318/orgs",
    repos_url: "https://api.github.com/users/ecn2318/repos",
    events_url: "https://api.github.com/users/ecn2318/events{/privacy}",
    received_events_url: "https://api.github.com/users/ecn2318/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ryansparker",
    id: 61031226,
    node_id: "MDQ6VXNlcjYxMDMxMjI2",
    avatar_url: "https://avatars.githubusercontent.com/u/61031226?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ryansparker",
    html_url: "https://github.com/ryansparker",
    followers_url: "https://api.github.com/users/ryansparker/followers",
    following_url:
      "https://api.github.com/users/ryansparker/following{/other_user}",
    gists_url: "https://api.github.com/users/ryansparker/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ryansparker/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ryansparker/subscriptions",
    organizations_url: "https://api.github.com/users/ryansparker/orgs",
    repos_url: "https://api.github.com/users/ryansparker/repos",
    events_url: "https://api.github.com/users/ryansparker/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ryansparker/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hackerd2020",
    id: 67505023,
    node_id: "MDQ6VXNlcjY3NTA1MDIz",
    avatar_url: "https://avatars.githubusercontent.com/u/67505023?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hackerd2020",
    html_url: "https://github.com/hackerd2020",
    followers_url: "https://api.github.com/users/hackerd2020/followers",
    following_url:
      "https://api.github.com/users/hackerd2020/following{/other_user}",
    gists_url: "https://api.github.com/users/hackerd2020/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hackerd2020/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hackerd2020/subscriptions",
    organizations_url: "https://api.github.com/users/hackerd2020/orgs",
    repos_url: "https://api.github.com/users/hackerd2020/repos",
    events_url: "https://api.github.com/users/hackerd2020/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hackerd2020/received_events",
    type: "User",
    site_admin: false,
  },
];
